"""empty message

Revision ID: 52f269a72d0f
Revises: dc0728e1a2f5
Create Date: 2025-06-25 19:27:20.429828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f269a72d0f'
down_revision = 'dc0728e1a2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frompost', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['frompost'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('frompost')

    # ### end Alembic commands ###
