"""empty message

Revision ID: dc0728e1a2f5
Revises: 869eda4ae9d2
Create Date: 2025-06-25 19:23:14.191805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0728e1a2f5'
down_revision = '869eda4ae9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Post', ['post'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post')

    # ### end Alembic commands ###
