"""empty message

Revision ID: fc275c899f2b
Revises: 52f269a72d0f
Create Date: 2025-06-25 19:28:53.888369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc275c899f2b'
down_revision = '52f269a72d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_constraint('Comment_frompost_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Post', ['frompost'], ['id'])

    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Media_post_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'])
        batch_op.drop_column('post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Media_post_fkey', 'Post', ['post'], ['id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Comment_frompost_fkey', 'User', ['frompost'], ['id'])

    # ### end Alembic commands ###
